#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

interface OpenApiDocument {
  components?: { schemas?: Record<string, Schema> };
  paths?: Record<string, Record<string, Operation>>;
}

interface Operation {
  operationId?: string;
  requestBody?: {
    content?: Record<string, { schema?: Schema }>;
  };
  responses?: Record<string, {
    content?: Record<string, { schema?: Schema }>;
  }>;
}

type Schema = {
  $ref?: string;
  type?: string;
  const?: string | number | boolean;
  enum?: Array<string | number | boolean>;
  anyOf?: Schema[];
  items?: Schema;
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
};

const inputPath = resolve(process.argv[2] ?? "docs/openapi.json");
const rawOutputPath = process.argv[3] ?? "packages/sdk/src/generated/openapi-types.ts";
const outputPath = rawOutputPath === "-" ? "-" : resolve(rawOutputPath);
const spec = JSON.parse(await readFile(inputPath, "utf8")) as OpenApiDocument;
const schemas = spec.components?.schemas ?? {};

const lines: string[] = [
  "/* eslint-disable */",
  "// Generated by scripts/generate-openapi-types.ts. Do not edit by hand.",
  "",
  "export interface OpenApiSchemas {",
];

for (const [name, schema] of Object.entries(schemas)) {
  lines.push(`  ${propertyKey(name)}: ${schemaToType(schema, { rootName: name, level: 1 })};`);
}
lines.push("}", "");

lines.push("export interface OpenApiOperations {");
for (const pathItem of Object.values(spec.paths ?? {})) {
  for (const operation of Object.values(pathItem)) {
    if (!operation.operationId) continue;
    lines.push(`  ${propertyKey(operation.operationId)}: {`);
    lines.push(`    request: ${operationRequestType(operation)};`);
    lines.push(`    response: ${operationResponseType(operation)};`);
    lines.push("  };");
  }
}
lines.push("}", "");

lines.push("export type OpenApiOperationId = keyof OpenApiOperations;");
lines.push("export type OpenApiOperationRequest<T extends OpenApiOperationId> = OpenApiOperations[T][\"request\"];");
lines.push("export type OpenApiOperationResponse<T extends OpenApiOperationId> = OpenApiOperations[T][\"response\"];");

const output = `${lines.join("\n")}\n`;
if (outputPath === "-") {
  process.stdout.write(output);
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output);
  console.log(`wrote ${outputPath}`);
}

function operationRequestType(operation: Operation): string {
  const schema = operation.requestBody?.content?.["application/json"]?.schema;
  return schema ? schemaToType(schema, { rootName: "request", level: 2 }) : "undefined";
}

function operationResponseType(operation: Operation): string {
  const success = Object.entries(operation.responses ?? {}).find(([status]) => status.startsWith("2"))?.[1];
  const schema = success?.content?.["application/json"]?.schema;
  if (schema) return schemaToType(schema, { rootName: "response", level: 2 });
  const sseSchema = success?.content?.["text/event-stream"]?.schema;
  return sseSchema ? "string" : "unknown";
}

function schemaToType(schema: Schema | undefined, context: { rootName: string; level: number }): string {
  if (!schema) return "unknown";
  if (schema.$ref) return `OpenApiSchemas[${JSON.stringify(refName(schema.$ref))}]`;
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum?.length) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.anyOf?.length) return schema.anyOf.map((entry) => schemaToType(entry, context)).join(" | ");
  if (!schema.type) return "unknown";
  if (schema.type === "string") return "string";
  if (schema.type === "number" || schema.type === "integer") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "array") {
    const item = schemaToType(schema.items, context);
    return `${item.includes("|") ? `(${item})` : item}[]`;
  }
  if (schema.type === "object") return objectToType(schema, context);
  return "unknown";
}

function objectToType(schema: Schema, context: { rootName: string; level: number }): string {
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const chunks: string[] = ["{"];
  for (const [name, property] of Object.entries(properties)) {
    chunks.push(`${indent(context.level)}${propertyKey(name)}${required.has(name) ? "" : "?"}: ${schemaToType(property, { ...context, level: context.level + 1 })};`);
  }
  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    chunks.push(`${indent(context.level)}[key: string]: ${schemaToType(schema.additionalProperties, { ...context, level: context.level + 1 })};`);
  } else if (schema.additionalProperties === true) {
    chunks.push(`${indent(context.level)}[key: string]: unknown;`);
  }
  chunks.push(`${indent(context.level - 1)}}`);
  return chunks.join("\n");
}

function refName(ref: string): string {
  return ref.split("/").at(-1) ?? ref;
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function indent(level: number): string {
  return "  ".repeat(Math.max(0, level));
}
